config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  # Auth
  get 'auth/auth0/callback' => 'auth0#callback'
  get 'auth/failure' => 'auth0#failure'
  get 'logout' => 'logout#logout'

  resources :talks
  resources :conferences, param: :abbr
  scope ":event" do
    post 'auth/auth0' => redirect('/auth/auth0')
    get '/speakers/registration' => 'speakers#new'
    resources :speakers, only: [:new, :show, :edit, :update, :create]
    get '/' => 'event#show'
  end
end

app/models/speaker.rb
class Speaker < ApplicationRecord
  belongs_to :conference
  has_many :talks_speakers
  has_many :talks, through: :talks_speakers
end

app/controllers/speakers_controller.rb
class Forbidden < ActionController::ActionControllerError; end

class SpeakersController < ApplicationController
  include Secured

  # GET /speakers
  # GET /speakers.json
  # def index
  #   @speakers = Speaker.all
  # end

  # GET /speakers/1
  # GET /speakers/1.json
  def show
    @speaker = Speaker.find_by(id: params[:id])
    render_404 unless @speaker
    authorize @speaker

    @conference = Conference.find_by(abbr: params[:event])
  end

  # GET /speakers/new
  def new
    @speaker_form = SpeakerForm.new
    @conference = Conference.find_by(abbr: params[:event])
    @speaker_form.load
  end

  # GET /speakers/1/edit
  def edit
    @speaker = Speaker.find_by(id: params[:id])
    authorize @speaker

    @speaker_form = SpeakerForm.new(speaker: @speaker)
    @speaker_form.load

    @conference = Conference.find_by(abbr: params[:event])
  end

  # POST /speakers
  # POST /speakers.json
  def create
    @conference = Conference.find_by(abbr: params[:event])

    @speaker_form = SpeakerForm.new(speaker_params, speaker: Speaker.new())
    @speaker_form.sub = @current_user[:extra][:raw_info][:sub]
    @speaker_form.email = @current_user[:info][:email]

    respond_to do |format|
      if @speaker_form.save
        format.html { redirect_to "/#{@conference.abbr}", notice: 'Speaker was successfully created.' }
        format.json { render :show, status: :created, location: @speaker }
      else
        format.html { render :new }
        format.json { render json: @speaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /speakers/1
  # PATCH/PUT /speakers/1.json
  def update
    @speaker = Speaker.find(params[:id])
    authorize @speaker

    @speaker_form = SpeakerForm.new(speaker_params, speaker: @speaker)
    @speaker_form.load

    respond_to do |format|
      if @speaker_form.save
        format.html { redirect_to speaker_path(id: @speaker.id), notice: 'Speaker was successfully updated.' }
        format.json { render :show, status: :ok, location: @speaker }
      else
        format.html { render :edit }
        format.json { render json: @speaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /speakers/1
  # DELETE /speakers/1.json
  def destroy
    @speaker.destroy
    authorize @speaker

    respond_to do |format|
      format.html { redirect_to speakers_url, notice: 'Speaker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def speaker_url
    case action_name
    when 'new'
      "/#{params[:event]}/speakers"
    when 'edit'
      "/#{params[:event]}/speakers/#{params[:id]}"
    end
  end

  helper_method :speaker_url
  private

  def pundit_user
    if @current_user
      Speaker.find_by(email: @current_user[:info][:email])
    end
  end

  # Only allow a list of trusted parameters through.
  def speaker_params
    params.require(:speaker).permit(:name,
                                    :sub,
                                    :email,
                                    :conference_id,
                                    talks_attributes: [:id, :title, :abstract, :conference_id, :_destroy])
  end
end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/views/speakers/_form.html.erb
<%= form_with(url: speaker_url, model: @speaker_form, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <p>Talks:</p>
  <div class="talk-fields">
    <%= form.fields_for :talks do |talk| %>
      <%= render 'speakers/talk_fields', :f => talk %>
    <% end %>
  </div>

  <% if  action_name == "new" || form.object.talks.size < 3 %>
    <p><%= link_to_add_talk_fields "Add Talk", form, :talks, class: 'add-talk btn btn-primary' %></p>
  <% else %>
    <p><%= link_to_add_talk_fields "Add Talk", form, :talks, class: 'add-talk btn btn-primary', style: "display: none" %></p>
  <% end %>


  <div class="field">
    <%= form.hidden_field :conference_id, value: @conference.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/speakers/_talk_fields.html.erb
<div class="talk-field">
  <p>Talk:</p>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :abstract %>
  <%= f.text_field :abstract %>

  <%= f.hidden_field :_destroy %>
  <%= link_to 'Delete', '#', class: 'remove_talk_field' %>
</div>

app/views/speakers/edit.html.erb
<!DOCTYPE html>
<html>

<header class="masthead">
  <div class="container h-100">

    <h1>Editing Profile</h1>

    <%= render 'form', speaker: @speaker %>

    <%= link_to 'Back', "/#{event_name}" %>
  </div>
</header>

app/views/speakers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @speakers.each do |speaker| %>
      <tr>
        <td><%= speaker.name %></td>
        <td><%= speaker.email %></td>
        <td><%= link_to 'Show', speaker_path(id: speaker.id) %></td>
        <td><%= link_to 'Edit', edit_speaker_path(id: speaker.id) %></td>
        <td><%= link_to 'Destroy', speaker_path(id: speaker.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_speaker_path %>

app/views/speakers/new.html.erb
<h1>New Profile</h1>

<%= render 'form', speaker: @speaker %>

app/views/speakers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @speaker.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @speaker.email %>
</p>

<%= link_to 'Edit', "/#{@conference.abbr}/speakers/#{@speaker.id}" %> |
<%= link_to 'Back', "/#{event_name}" %>